{% set name = "seclea_ai" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://github.com/seclea/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  # Leaving this in just as reference if we move back to GitHub releases.

  sha256: 80024380a5514f91a8c9a17a68d7fd1eb38855ba36552f5ec23dd493a26a11ab


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - {{ compiler('c') }}
    - cmake
    - python
    - pip
  run:
    - {{ compiler('c') }}
    - cmake
    - python
    - dill >=0.3.4
    - decorator
    - pandas >=1.3.0
    - pickledb >=0.9.2
    - requests >=2.0.0
    - wrapt

test:
  imports:
    - seclea_ai
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/seclea/seclea_ai
  license: LicenseRef-LICENSE.txt
  license_file: LICENSE.txt
  summary: Integration with Seclea Platform
  description: |
    seclea_ai is a package for integrating your AI application development with the Seclea Platform
    for responsible, fair and transparent AI applications. See seclea.com for more details.
  doc_url: https://docs.seclea.com/
  dev_url: https://github.com/seclea/seclea-ai.git

extra:
  recipe-maintainers:
    - rogermilroy
