{% set name = "seclea_ai" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://github.com/seclea/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  # Leaving this in just as reference if we move back to GitHub releases.
  sha256: 281446b1f90aa4a2cf15feb72b121e6d4627a84b2f65f11cacac6fed6b8b3577

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dill >=0.3.4
    - pandas >=1.3.0
    - pickledb >=0.9.2
    - requests >=2.0.0
    - zstandard >=0.15.2

test:
  imports:
    - seclea_ai
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/seclea/seclea_ai
  license: LicenseRef-LICENSE.txt
  license_file: LICENSE.txt
  summary: Integration with Seclea Platform
  description: |
    seclea_ai is a package for integrating your AI application development with the Seclea Platform
    for responsible, fair and transparent AI applications. See seclea.com for more details.
  doc_url: https://docs.seclea.com/
  dev_url: https://github.com/seclea/seclea-ai.git

extra:
  recipe-maintainers:
    - rogermilroy
